---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/triowolf/repositories/TrioWolf/
    - export BUILD_PATH=build/

    # Install npm dependencies
    - /usr/local/bin/npm install

    # Build the React project
    - /usr/local/bin/npm run build

    # Remove old files in the deploy path (optional, but recommended to avoid conflicts)
    - /bin/rm -rf ${DEPLOY_PATH}*

    # Copy the built files to the deploy path
    - /bin/cp -r ${BUILD_PATH}* ${DEPLOY_PATH}
